Pya 28 hero and about us component
pizzapy/pizzapy-website pull request #6
Opened 2024-05-17 05:05 UTC by cristoph143

# Pull Request Summary: PYA-28 Hero and About Us Component

**Branch:** `PYA-28-Hero-and-About-Us-Component`  
**Base Branch:** `develop`  
**Author:** @cristoph143  
**Reviewers:** @Luzefiru, @jackjk521  
**Status:** Ready to merge

## Description

This pull request refactors the landing page of the PizzaPy website, adding new components and enhancing the overall layout. The key changes include the addition of the Hero and About Us sections, as well as a new Call to Action (CTA) and Sponsors section.

## Changes

### Commits

1. **Refactor landing page layout and update partials in index.html**
   - Updated the layout structure and partials for the landing page.
2. **Refactor landing page layout and add sponsors partial**
   - Added a new section for displaying sponsor logos.
3. **Refactor landing page layout and add CTA section**
   - Added a new Call to Action section to encourage user engagement.

### Visual Enhancements

- **Hero Section**: Engaging hero section with a background image and prominent title.
- **About Us Section**: Informative section detailing the community, expertise, and goals.
- **Call to Action**: Eye-catching section to encourage users to join and follow on social media.
- **Sponsors Section**: Continuous scrolling sponsor logos for better visual appeal and recognition.

## Next Steps
# Pull Request Summary: PYA-28 Hero and About Us Component

**Branch:** `PYA-28-Hero-and-About-Us-Component`  
**Base Branch:** `develop`  
**Author:** @cristoph143  
**Reviewers:** @Luzefiru, @jackjk521  
**Status:** Ready to merge

## Description

This pull request refactors the landing page of the PizzaPy website, adding new components and enhancing the overall layout. The key changes include the addition of the Hero and About Us sections, as well as a new Call to Action (CTA) and Sponsors section.

## Changes

### Commits

1. **Refactor landing page layout and update partials in index.html**
   - Updated the layout structure and partials for the landing page.
2. **Refactor landing page layout and add sponsors partial**
   - Added a new section for displaying sponsor logos.
3. **Refactor landing page layout and add CTA section**
   - Added a new Call to Action section to encourage user engagement.

### Visual Enhancements

- **Hero Section**: Engaging hero section with a background image and prominent title.
- **About Us Section**: Informative section detailing the community, expertise, and goals.
- **Call to Action**: Eye-catching section to encourage users to join and follow on social media.
- **Sponsors Section**: Continuous scrolling sponsor logos for better visual appeal and recognition.

## Next Steps

- [ ] Review and approve the changes.
- [ ] Merge the branch into `develop`.
- [ ] Close related issues using closing keywords if applicable.

Feel free to provide any feedback or suggestions for further improvements.

- [ ] Review and approve the changes.
- [ ] Merge the branch into `develop`.
- [ ] Close related issues using closing keywords if applicable.

Feel free to provide any feedback or suggestions for further improvements.

2024-05-18 07:58 UTC, jackjk521 requested changes
Review the code and tested locally. Please refer to the comments section on the Jira card below:

https://hydra-dev.atlassian.net/browse/PYA-28?atlOrigin=eyJpIjoiMGY2NmVkZjYyMDFlNDBlYjk3OTNlMTNiMTY1ZDNmMGMiLCJwIjoiaiJ9

2024-05-19 05:42 UTC, Luzefiru requested changes
I left some comments on parts that require changes. Good work so far.

2024-05-19 05:42 UTC, Luzefiru commented on PizzaPyWebApp/templates/partials/landing/about_us.html
> +            <button class="px-4 py-2 font-bold bg-purple-600 rounded hover:bg-purple-800">
Should be an `<a href="/about_us">` tag.

Also, add proper spacing to match the Figma design as shown here:
![image](https://github.com/pizzapy/pizzapy-website/assets/105530193/af4fcb7f-902a-43cf-b02c-b6ccf26572ff)

**Quick Figma Tip**: Click on an element and hold <kbd>ALT</kbd> while hovering on other elements to see the spacing between them.

2024-05-19 05:42 UTC, Luzefiru commented on PizzaPyWebApp/templates/partials/landing/about_us.html
> +    <div class="flex flex-col items-center gap-12 md:flex-row">
Change `<div class="flex flex-col items-center gap-12 md:flex-row">` to `<div class="flex flex-col items-center gap-20 md:flex-row">` to match the Figma design's spacing.

2024-05-19 05:42 UTC, Luzefiru commented on PizzaPyWebApp/templates/partials/landing/hero.html
> +    <img src="https://via.placeholder.com/1500x800" alt="Background Image"
This can be removed because the Hero will not have a static background image. Just the generic background color.

2024-05-19 05:42 UTC, Luzefiru commented on PizzaPyWebApp/templates/partials/landing/cta.html
> +    <img src="https://via.placeholder.com/1500x800" alt="Background Image"
Same comment with Hero section's background image.

2024-05-19 05:42 UTC, Luzefiru commented on PizzaPyWebApp/templates/partials/landing/cta.html
> +                <button
The button background color should be consistent with the other buttons: `#5248FF`.

2024-05-19 09:58 UTC, Luzefiru commented
My comments have been resolved, one last thing: the marquee container should not clip the background image. Otherwise, LGTM.

![image](https://github.com/pizzapy/pizzapy-website/assets/105530193/613804d5-bb77-4f18-9587-598e39208e70)

2024-05-19 12:39 UTC, Luzefiru approved these changes

2024-05-20 14:21 UTC, merged